-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklist_articles.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ce_worklist_articles (
  cewa_id BIGSERIAL NOT NULL,
  cewa_page_id INT NOT NULL,
  cewa_page_title TEXT NOT NULL,
  cewa_ceil_id BIGINT NOT NULL,
  PRIMARY KEY(cewa_id)
);

CREATE INDEX ce_worklist_articles_ceil_id ON ce_worklist_articles (cewa_ceil_id);
