-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-cea_country_code.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE ce_address
  ADD cea_country_code TEXT DEFAULT NULL;

CREATE INDEX cea_country_code ON ce_address (cea_country_code);
