-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_event_wikis.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ce_event_wikis (
  ceew_id BIGSERIAL NOT NULL,
  ceew_event_id BIGINT NOT NULL,
  ceew_wiki TEXT NOT NULL,
  PRIMARY KEY(ceew_id)
);

CREATE UNIQUE INDEX ce_event_wikis_event_id_wiki ON ce_event_wikis (ceew_event_id, ceew_wiki);
