-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklist_pages.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ce_worklist_pages (
  cewp_id SERIAL NOT NULL,
  cewp_wiki VARCHAR(64) NOT NULL,
  cewp_page_prefixedtext TEXT NOT NULL,
  cewp_user_id INT NOT NULL,
  cewp_cew_id INT NOT NULL,
  cewp_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(cewp_id)
);

CREATE INDEX ce_worklist_pages_cewp_cew_id ON ce_worklist_pages (cewp_cew_id);

CREATE UNIQUE INDEX ce_worklist_pages_wiki_page_cew_id ON ce_worklist_pages (
  cewp_wiki, cewp_page_prefixedtext,
  cewp_cew_id
);
