-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_invitation_lists.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ce_invitation_lists (
  ceil_id BIGSERIAL NOT NULL,
  ceil_name TEXT NOT NULL,
  ceil_event_id BIGINT DEFAULT NULL,
  ceil_status INT NOT NULL,
  ceil_user_id INT NOT NULL,
  ceil_wiki TEXT NOT NULL,
  ceil_created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ceil_id)
);

CREATE INDEX ce_invitation_lists_event_id ON ce_invitation_lists (ceil_event_id);

CREATE INDEX ce_invitation_lists_wiki ON ce_invitation_lists (ceil_wiki);

CREATE INDEX ce_invitation_lists_user_wiki ON ce_invitation_lists (ceil_user_id, ceil_wiki);
