-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-cleanup-country.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE ce_address
  DROP cea_country;

ALTER TABLE ce_address
  ALTER cea_country_code
SET
  NOT NULL;
