-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_event_topics.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ce_event_topics (
  ceet_id BIGSERIAL NOT NULL,
  ceet_event_id BIGINT NOT NULL,
  ceet_topic TEXT NOT NULL,
  PRIMARY KEY(ceet_id)
);

CREATE UNIQUE INDEX ce_event_topics_event_id_topic ON ce_event_topics (ceet_event_id, ceet_topic);
