-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_invitation_list_articles.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ce_invitation_list_articles (
  ceila_id BIGSERIAL NOT NULL,
  ceila_page_id INT NOT NULL,
  ceila_page_title TEXT NOT NULL,
  ceila_ceil_id BIGINT NOT NULL,
  PRIMARY KEY(ceila_id)
);

CREATE INDEX ce_invitation_list_articles_ceil_id ON ce_invitation_list_articles (ceila_ceil_id);
