-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklists.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ce_worklists (
  cew_id SERIAL NOT NULL,
  cew_wiki VARCHAR(64) NOT NULL,
  cew_page_id INT NOT NULL,
  cew_page_prefixedtext TEXT NOT NULL,
  cew_user_id INT NOT NULL,
  cew_username TEXT DEFAULT NULL,
  cew_timestamp TIMESTAMPTZ NOT NULL,
  cew_content_rev BIGINT DEFAULT NULL,
  PRIMARY KEY(cew_id)
);

CREATE INDEX ce_worklists_user_id ON ce_worklists (cew_user_id);

CREATE UNIQUE INDEX ce_worklists_wiki_page_id ON ce_worklists (cew_wiki, cew_page_id);
