-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklist_events.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ce_worklist_events (
  cewe_id SERIAL NOT NULL,
  cewe_cew_id BIGINT NOT NULL,
  cewe_event_id BIGINT NOT NULL,
  PRIMARY KEY(cewe_id)
);

CREATE UNIQUE INDEX ce_worklist_events_worklist_event ON ce_worklist_events (cewe_cew_id, cewe_event_id);
