-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db_patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE campaign_events (
  event_id BIGSERIAL NOT NULL,
  event_name TEXT NOT NULL,
  event_page_namespace INT NOT NULL,
  event_page_title TEXT NOT NULL,
  event_page_wiki TEXT NOT NULL,
  event_chat_url TEXT NOT NULL,
  event_tracking_tool TEXT NOT NULL,
  event_tracking_url TEXT NOT NULL,
  event_status INT NOT NULL,
  event_start TIMESTAMPTZ NOT NULL,
  event_end TIMESTAMPTZ NOT NULL,
  event_type TEXT NOT NULL,
  event_meeting_type INT NOT NULL,
  event_meeting_url TEXT NOT NULL,
  event_meeting_country TEXT NOT NULL,
  event_meeting_address TEXT NOT NULL,
  event_created_at TIMESTAMPTZ NOT NULL,
  event_last_edit TIMESTAMPTZ NOT NULL,
  event_deleted_at TIMESTAMPTZ DEFAULT NULL,
  PRIMARY KEY(event_id)
);

CREATE UNIQUE INDEX event_page ON campaign_events (
  event_page_wiki, event_page_namespace,
  event_page_title
);


CREATE TABLE ce_participants (
  cep_id BIGSERIAL NOT NULL,
  cep_event_id BIGINT NOT NULL,
  cep_user_id INT NOT NULL,
  cep_registered_at TIMESTAMPTZ NOT NULL,
  cep_unregistered_at TIMESTAMPTZ DEFAULT NULL,
  PRIMARY KEY(cep_id)
);

CREATE UNIQUE INDEX cep_event_participant ON ce_participants (cep_event_id, cep_user_id);


CREATE TABLE ce_organizers (
  ceo_id BIGSERIAL NOT NULL,
  ceo_event_id BIGINT NOT NULL,
  ceo_user_id INT NOT NULL,
  ceo_role_id BIGINT NOT NULL,
  PRIMARY KEY(ceo_id)
);

CREATE UNIQUE INDEX ceo_event_user_role ON ce_organizers (
  ceo_event_id, ceo_user_id, ceo_role_id
);
