-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db_patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE campaign_events (
  event_id BIGSERIAL NOT NULL,
  event_name TEXT NOT NULL,
  event_page_namespace INT NOT NULL,
  event_page_title TEXT NOT NULL,
  event_page_wiki TEXT NOT NULL,
  event_page_prefixedtext TEXT NOT NULL,
  event_chat_url TEXT NOT NULL,
  event_status INT NOT NULL,
  event_timezone TEXT NOT NULL,
  event_start_local TEXT NOT NULL,
  event_start_utc TIMESTAMPTZ NOT NULL,
  event_end_local TEXT NOT NULL,
  event_end_utc TIMESTAMPTZ NOT NULL,
  event_types INT DEFAULT 0 NOT NULL,
  event_track_contributions SMALLINT DEFAULT 0 NOT NULL,
  event_meeting_type INT NOT NULL,
  event_meeting_url TEXT NOT NULL,
  event_created_at TIMESTAMPTZ NOT NULL,
  event_last_edit TIMESTAMPTZ NOT NULL,
  event_deleted_at TIMESTAMPTZ DEFAULT NULL,
  event_is_test_event SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(event_id)
);

CREATE UNIQUE INDEX event_page ON campaign_events (
  event_page_wiki, event_page_namespace,
  event_page_title
);

CREATE INDEX event_id_deleted ON campaign_events (event_id, event_deleted_at);

CREATE INDEX event_timezone_id ON campaign_events (event_timezone, event_id);


CREATE TABLE ce_participants (
  cep_id BIGSERIAL NOT NULL,
  cep_event_id BIGINT NOT NULL,
  cep_user_id INT NOT NULL,
  cep_private BOOLEAN NOT NULL,
  cep_registered_at TIMESTAMPTZ NOT NULL,
  cep_unregistered_at TIMESTAMPTZ DEFAULT NULL,
  cep_first_answer_timestamp TIMESTAMPTZ DEFAULT NULL,
  cep_aggregation_timestamp TIMESTAMPTZ DEFAULT NULL,
  PRIMARY KEY(cep_id)
);

CREATE UNIQUE INDEX cep_event_participant ON ce_participants (cep_event_id, cep_user_id);

CREATE INDEX cep_event_unregistered ON ce_participants (
  cep_event_id, cep_unregistered_at
);

CREATE INDEX cep_user_unregistered_event ON ce_participants (
  cep_user_id, cep_unregistered_at,
  cep_event_id
);


CREATE TABLE ce_organizers (
  ceo_id BIGSERIAL NOT NULL,
  ceo_event_id BIGINT NOT NULL,
  ceo_user_id INT NOT NULL,
  ceo_roles BIGINT NOT NULL,
  ceo_created_at TIMESTAMPTZ NOT NULL,
  ceo_deleted_at TIMESTAMPTZ DEFAULT NULL,
  ceo_agreement_timestamp TIMESTAMPTZ DEFAULT NULL,
  PRIMARY KEY(ceo_id)
);

CREATE UNIQUE INDEX ceo_event_user ON ce_organizers (ceo_event_id, ceo_user_id);

CREATE INDEX ceo_user_event ON ce_organizers (ceo_user_id, ceo_event_id);


CREATE TABLE ce_address (
  cea_id BIGSERIAL NOT NULL,
  cea_full_address TEXT NOT NULL,
  cea_country_code TEXT NOT NULL,
  PRIMARY KEY(cea_id)
);

CREATE INDEX cea_country_code ON ce_address (cea_country_code);


CREATE TABLE ce_event_address (
  ceea_id BIGSERIAL NOT NULL,
  ceea_event BIGINT NOT NULL,
  ceea_address BIGINT NOT NULL,
  PRIMARY KEY(ceea_id)
);

CREATE UNIQUE INDEX ceea_event_address ON ce_event_address (ceea_event, ceea_address);


CREATE TABLE ce_tracking_tools (
  cett_id BIGSERIAL NOT NULL,
  cett_event BIGINT NOT NULL,
  cett_tool_id INT NOT NULL,
  cett_tool_event_id TEXT NOT NULL,
  cett_sync_status INT NOT NULL,
  cett_last_sync TIMESTAMPTZ DEFAULT NULL,
  PRIMARY KEY(cett_id)
);

CREATE UNIQUE INDEX cett_event_tool_teid ON ce_tracking_tools (
  cett_event, cett_tool_id, cett_tool_event_id
);


CREATE TABLE ce_event_questions (
  ceeq_id BIGSERIAL NOT NULL,
  ceeq_event_id BIGINT NOT NULL,
  ceeq_question_id INT NOT NULL,
  PRIMARY KEY(ceeq_id)
);

CREATE UNIQUE INDEX ceeq_event_question ON ce_event_questions (ceeq_event_id, ceeq_question_id);


CREATE TABLE ce_question_answers (
  ceqa_id BIGSERIAL NOT NULL,
  ceqa_event_id BIGINT NOT NULL,
  ceqa_user_id INT NOT NULL,
  ceqa_question_id INT NOT NULL,
  ceqa_answer_option INT DEFAULT NULL,
  ceqa_answer_text TEXT DEFAULT NULL,
  PRIMARY KEY(ceqa_id)
);

CREATE UNIQUE INDEX ceqa_event_user_question ON ce_question_answers (
  ceqa_event_id, ceqa_user_id, ceqa_question_id
);


CREATE TABLE ce_question_aggregation (
  ceqag_id BIGSERIAL NOT NULL,
  ceqag_event_id BIGINT NOT NULL,
  ceqag_question_id INT NOT NULL,
  ceqag_answer_option INT NOT NULL,
  ceqag_answers_amount INT NOT NULL,
  PRIMARY KEY(ceqag_id)
);

CREATE UNIQUE INDEX ceqag_event_question_option ON ce_question_aggregation (
  ceqag_event_id, ceqag_question_id,
  ceqag_answer_option
);


CREATE TABLE ce_invitation_lists (
  ceil_id BIGSERIAL NOT NULL,
  ceil_name TEXT NOT NULL,
  ceil_event_id BIGINT DEFAULT NULL,
  ceil_status INT NOT NULL,
  ceil_user_id INT NOT NULL,
  ceil_wiki TEXT NOT NULL,
  ceil_created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ceil_id)
);

CREATE INDEX ce_invitation_lists_event_id ON ce_invitation_lists (ceil_event_id);

CREATE INDEX ce_invitation_lists_wiki ON ce_invitation_lists (ceil_wiki);

CREATE INDEX ce_invitation_lists_user_wiki ON ce_invitation_lists (ceil_user_id, ceil_wiki);


CREATE TABLE ce_worklist_articles (
  cewa_id BIGSERIAL NOT NULL,
  cewa_page_id INT NOT NULL,
  cewa_page_title TEXT NOT NULL,
  cewa_ceil_id BIGINT NOT NULL,
  PRIMARY KEY(cewa_id)
);

CREATE INDEX ce_worklist_articles_ceil_id ON ce_worklist_articles (cewa_ceil_id);


CREATE TABLE ce_invitation_list_users (
  ceilu_id BIGSERIAL NOT NULL,
  ceilu_user_id INT NOT NULL,
  ceilu_ceil_id BIGINT NOT NULL,
  ceilu_score INT NOT NULL,
  PRIMARY KEY(ceilu_id)
);

CREATE INDEX ce_invitation_list_users_ceil_id ON ce_invitation_list_users (ceilu_ceil_id);

CREATE INDEX ce_invitation_list_users_ceilu_user_id ON ce_invitation_list_users (ceilu_user_id);


CREATE TABLE ce_event_wikis (
  ceew_id BIGSERIAL NOT NULL,
  ceew_event_id BIGINT NOT NULL,
  ceew_wiki TEXT NOT NULL,
  PRIMARY KEY(ceew_id)
);

CREATE UNIQUE INDEX ce_event_wikis_event_id_wiki ON ce_event_wikis (ceew_event_id, ceew_wiki);


CREATE TABLE ce_event_topics (
  ceet_id BIGSERIAL NOT NULL,
  ceet_event_id BIGINT NOT NULL,
  ceet_topic TEXT NOT NULL,
  PRIMARY KEY(ceet_id)
);

CREATE UNIQUE INDEX ce_event_topics_event_id_topic ON ce_event_topics (ceet_event_id, ceet_topic);


CREATE TABLE ce_event_contributions (
  cec_id BIGSERIAL NOT NULL,
  cec_event_id BIGINT NOT NULL,
  cec_user_id BIGINT NOT NULL,
  cec_user_name TEXT DEFAULT NULL,
  cec_wiki VARCHAR(64) NOT NULL,
  cec_page_id INT NOT NULL,
  cec_page_prefixedtext TEXT NOT NULL,
  cec_revision_id BIGINT NOT NULL,
  cec_edit_flags INT NOT NULL,
  cec_bytes_delta INT NOT NULL,
  cec_links_delta SMALLINT NOT NULL,
  cec_timestamp TIMESTAMPTZ NOT NULL,
  cec_deleted SMALLINT NOT NULL,
  PRIMARY KEY(cec_id)
);

CREATE INDEX cec_wiki_page_id ON ce_event_contributions (cec_wiki, cec_page_id);

CREATE UNIQUE INDEX cec_wiki_revision ON ce_event_contributions (cec_wiki, cec_revision_id);

CREATE INDEX cec_event_user ON ce_event_contributions (cec_event_id, cec_user_id);

CREATE INDEX cec_user_id_name ON ce_event_contributions (cec_user_id, cec_user_name);
