-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_event_topics.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_event_topics (
  ceet_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceet_event_id BIGINT UNSIGNED NOT NULL,
  ceet_topic VARBINARY(64) NOT NULL,
  UNIQUE INDEX ce_event_topics_event_id_topic (ceet_event_id, ceet_topic),
  PRIMARY KEY(ceet_id)
) /*$wgDBTableOptions*/;
