-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_event_wikis.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_event_wikis (
  ceew_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceew_event_id BIGINT UNSIGNED NOT NULL,
  ceew_wiki VARBINARY(64) NOT NULL,
  UNIQUE INDEX ce_event_wikis_event_id_wiki (ceew_event_id, ceew_wiki),
  PRIMARY KEY(ceew_id)
) /*$wgDBTableOptions*/;
