-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklist_articles.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_worklist_articles (
  cewa_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  cewa_page_id INT UNSIGNED NOT NULL,
  cewa_page_title VARBINARY(255) NOT NULL,
  cewa_ceil_id BIGINT UNSIGNED NOT NULL,
  INDEX ce_worklist_articles_ceil_id (cewa_ceil_id),
  PRIMARY KEY(cewa_id)
) /*$wgDBTableOptions*/;
