-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklist_events.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_worklist_events (
  cewe_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cewe_cew_id BIGINT UNSIGNED NOT NULL,
  cewe_event_id BIGINT UNSIGNED NOT NULL,
  UNIQUE INDEX ce_worklist_events_worklist_event (cewe_cew_id, cewe_event_id),
  PRIMARY KEY(cewe_id)
) /*$wgDBTableOptions*/;
