-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_invitation_list_articles.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_invitation_list_articles (
  ceila_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceila_page_id INT UNSIGNED NOT NULL,
  ceila_page_title VARBINARY(255) NOT NULL,
  ceila_ceil_id BIGINT UNSIGNED NOT NULL,
  INDEX ce_invitation_list_articles_ceil_id (ceila_ceil_id),
  PRIMARY KEY(ceila_id)
) /*$wgDBTableOptions*/;
