-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-cep_hide_contribution_association_prompt.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/ce_participants
  ADD cep_hide_contribution_association_prompt TINYINT(1) DEFAULT 0 NOT NULL;
