-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-cleanup-country.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/ce_address
  DROP cea_country,
  CHANGE cea_country_code cea_country_code BINARY(2) NOT NULL;
