-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_event_contributions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_event_contributions (
  cec_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  cec_event_id BIGINT UNSIGNED NOT NULL,
  cec_user_id BIGINT UNSIGNED NOT NULL,
  cec_user_name VARBINARY(255) DEFAULT NULL,
  cec_wiki VARCHAR(64) NOT NULL,
  cec_page_id INT UNSIGNED NOT NULL,
  cec_page_prefixedtext VARBINARY(512) NOT NULL,
  cec_revision_id BIGINT UNSIGNED NOT NULL,
  cec_edit_flags INT NOT NULL,
  cec_bytes_delta INT NOT NULL,
  cec_links_delta SMALLINT NOT NULL,
  cec_timestamp BINARY(14) NOT NULL,
  cec_deleted TINYINT(1) NOT NULL,
  INDEX cec_wiki_page_id (cec_wiki, cec_page_id),
  UNIQUE INDEX cec_wiki_revision (cec_wiki, cec_revision_id),
  INDEX cec_event_user (cec_event_id, cec_user_id),
  INDEX cec_user_id_name (cec_user_id, cec_user_name),
  PRIMARY KEY(cec_id)
) /*$wgDBTableOptions*/;
