-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklists.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_worklists (
  cew_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cew_wiki VARCHAR(64) NOT NULL,
  cew_page_id INT UNSIGNED NOT NULL,
  cew_page_prefixedtext VARBINARY(512) NOT NULL,
  cew_user_id INT UNSIGNED NOT NULL,
  cew_username VARBINARY(255) DEFAULT NULL,
  cew_timestamp BINARY(14) NOT NULL,
  cew_content_rev BIGINT UNSIGNED DEFAULT NULL,
  INDEX ce_worklists_user_id (cew_user_id),
  UNIQUE INDEX ce_worklists_wiki_page_id (cew_wiki, cew_page_id),
  PRIMARY KEY(cew_id)
) /*$wgDBTableOptions*/;
