-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce-event-goals.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_event_goals (
  ceeg_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceeg_event_id BIGINT UNSIGNED NOT NULL,
  ceeg_goals LONGBLOB NOT NULL,
  INDEX ceeg_event_id (ceeg_event_id),
  PRIMARY KEY(ceeg_id)
) /*$wgDBTableOptions*/;
