-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklist_pages.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_worklist_pages (
  cewp_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cewp_wiki VARCHAR(64) NOT NULL,
  cewp_page_prefixedtext VARBINARY(512) NOT NULL,
  cewp_user_id INT UNSIGNED NOT NULL,
  cewp_cew_id INT UNSIGNED NOT NULL,
  cewp_timestamp BINARY(14) NOT NULL,
  INDEX ce_worklist_pages_cewp_cew_id (cewp_cew_id),
  UNIQUE INDEX ce_worklist_pages_wiki_page_cew_id (
    cewp_wiki, cewp_page_prefixedtext,
    cewp_cew_id
  ),
  PRIMARY KEY(cewp_id)
) /*$wgDBTableOptions*/;
