-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db_patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/campaign_events (
  event_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  event_name VARBINARY(255) NOT NULL,
  event_page_namespace INT UNSIGNED NOT NULL,
  event_page_title VARBINARY(255) NOT NULL,
  event_page_wiki VARBINARY(64) NOT NULL,
  event_page_prefixedtext VARBINARY(512) NOT NULL,
  event_chat_url BLOB NOT NULL,
  event_status INT NOT NULL,
  event_timezone VARBINARY(64) NOT NULL,
  event_start_local BINARY(14) NOT NULL,
  event_start_utc BINARY(14) NOT NULL,
  event_end_local BINARY(14) NOT NULL,
  event_end_utc BINARY(14) NOT NULL,
  event_type VARBINARY(255) NOT NULL,
  event_meeting_type INT NOT NULL,
  event_meeting_url BLOB NOT NULL,
  event_created_at BINARY(14) NOT NULL,
  event_last_edit BINARY(14) NOT NULL,
  event_deleted_at BINARY(14) DEFAULT NULL,
  event_answers_status INT NOT NULL,
  UNIQUE INDEX event_page (
    event_page_wiki, event_page_namespace,
    event_page_title
  ),
  INDEX event_id_deleted (event_id, event_deleted_at),
  INDEX event_timezone_id (event_timezone, event_id),
  PRIMARY KEY(event_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_participants (
  cep_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  cep_event_id BIGINT UNSIGNED NOT NULL,
  cep_user_id INT UNSIGNED NOT NULL,
  cep_private TINYINT(1) NOT NULL,
  cep_registered_at BINARY(14) NOT NULL,
  cep_unregistered_at BINARY(14) DEFAULT NULL,
  cep_first_answer_timestamp BINARY(14) DEFAULT NULL,
  cep_aggregation_timestamp BINARY(14) DEFAULT NULL,
  UNIQUE INDEX cep_event_participant (cep_event_id, cep_user_id),
  INDEX cep_event_unregistered (
    cep_event_id, cep_unregistered_at
  ),
  INDEX cep_user_unregistered_event (
    cep_user_id, cep_unregistered_at,
    cep_event_id
  ),
  PRIMARY KEY(cep_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_organizers (
  ceo_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceo_event_id BIGINT UNSIGNED NOT NULL,
  ceo_user_id INT UNSIGNED NOT NULL,
  ceo_roles BIGINT UNSIGNED NOT NULL,
  ceo_created_at BINARY(14) NOT NULL,
  ceo_deleted_at BINARY(14) DEFAULT NULL,
  ceo_agreement_timestamp BINARY(14) DEFAULT NULL,
  UNIQUE INDEX ceo_event_user (ceo_event_id, ceo_user_id),
  INDEX ceo_user_event (ceo_user_id, ceo_event_id),
  PRIMARY KEY(ceo_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_address (
  cea_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  cea_full_address BLOB NOT NULL,
  cea_country VARBINARY(255) DEFAULT NULL,
  PRIMARY KEY(cea_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_event_address (
  ceea_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceea_event BIGINT UNSIGNED NOT NULL,
  ceea_address BIGINT UNSIGNED NOT NULL,
  UNIQUE INDEX ceea_event_address (ceea_event, ceea_address),
  PRIMARY KEY(ceea_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_tracking_tools (
  cett_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  cett_event BIGINT UNSIGNED NOT NULL,
  cett_tool_id INT NOT NULL,
  cett_tool_event_id VARBINARY(512) NOT NULL,
  cett_sync_status INT NOT NULL,
  cett_last_sync BINARY(14) DEFAULT NULL,
  UNIQUE INDEX cett_event_tool_teid (
    cett_event, cett_tool_id, cett_tool_event_id
  ),
  PRIMARY KEY(cett_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_event_questions (
  ceeq_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceeq_event_id BIGINT UNSIGNED NOT NULL,
  ceeq_question_id INT UNSIGNED NOT NULL,
  UNIQUE INDEX ceeq_event_question (ceeq_event_id, ceeq_question_id),
  PRIMARY KEY(ceeq_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_question_answers (
  ceqa_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceqa_event_id BIGINT UNSIGNED NOT NULL,
  ceqa_user_id INT UNSIGNED NOT NULL,
  ceqa_question_id INT UNSIGNED NOT NULL,
  ceqa_answer_option INT UNSIGNED DEFAULT NULL,
  ceqa_answer_text BLOB DEFAULT NULL,
  UNIQUE INDEX ceqa_event_user_question (
    ceqa_event_id, ceqa_user_id, ceqa_question_id
  ),
  PRIMARY KEY(ceqa_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_question_aggregation (
  ceqag_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceqag_event_id BIGINT UNSIGNED NOT NULL,
  ceqag_question_id INT UNSIGNED NOT NULL,
  ceqag_answer_option INT UNSIGNED NOT NULL,
  ceqag_answers_amount INT UNSIGNED NOT NULL,
  UNIQUE INDEX ceqag_event_question (
    ceqag_event_id, ceqag_question_id
  ),
  PRIMARY KEY(ceqag_id)
) /*$wgDBTableOptions*/;
