-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db_patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/campaign_events (
  event_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  event_name VARBINARY(255) NOT NULL,
  event_page_namespace INT UNSIGNED NOT NULL,
  event_page_title VARBINARY(255) NOT NULL,
  event_page_wiki VARBINARY(64) NOT NULL,
  event_page_prefixedtext VARBINARY(512) NOT NULL,
  event_chat_url BLOB NOT NULL,
  event_tracking_tool_id INT DEFAULT NULL,
  event_tracking_tool_event_id BLOB DEFAULT NULL,
  event_status INT NOT NULL,
  event_timezone VARBINARY(64) NOT NULL,
  event_start_local BINARY(14) NOT NULL,
  event_start_utc BINARY(14) NOT NULL,
  event_end_local BINARY(14) NOT NULL,
  event_end_utc BINARY(14) NOT NULL,
  event_type VARBINARY(255) NOT NULL,
  event_meeting_type INT NOT NULL,
  event_meeting_url BLOB NOT NULL,
  event_meeting_country VARBINARY(255) NOT NULL,
  event_meeting_address BLOB NOT NULL,
  event_created_at BINARY(14) NOT NULL,
  event_last_edit BINARY(14) NOT NULL,
  event_deleted_at BINARY(14) DEFAULT NULL,
  UNIQUE INDEX event_page (
    event_page_wiki, event_page_namespace,
    event_page_title
  ),
  INDEX event_id_deleted (event_id, event_deleted_at),
  INDEX event_timezone_id (event_timezone, event_id),
  PRIMARY KEY(event_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_participants (
  cep_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  cep_event_id BIGINT UNSIGNED NOT NULL,
  cep_user_id INT UNSIGNED NOT NULL,
  cep_registered_at BINARY(14) NOT NULL,
  cep_unregistered_at BINARY(14) DEFAULT NULL,
  UNIQUE INDEX cep_event_participant (cep_event_id, cep_user_id),
  INDEX cep_event_unregistered (
    cep_event_id, cep_unregistered_at
  ),
  INDEX cep_user_unregistered_event (
    cep_user_id, cep_unregistered_at,
    cep_event_id
  ),
  PRIMARY KEY(cep_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_organizers (
  ceo_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceo_event_id BIGINT UNSIGNED NOT NULL,
  ceo_user_id INT UNSIGNED NOT NULL,
  ceo_role_id BIGINT UNSIGNED NOT NULL,
  ceo_created_at BINARY(14) NOT NULL,
  ceo_deleted_at BINARY(14) DEFAULT NULL,
  UNIQUE INDEX ceo_event_user_role (
    ceo_event_id, ceo_user_id, ceo_role_id
  ),
  INDEX ceo_user_event (ceo_user_id, ceo_event_id),
  PRIMARY KEY(ceo_id)
) /*$wgDBTableOptions*/;
