-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db_patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/campaign_events (
  event_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  event_name VARBINARY(255) NOT NULL,
  event_page_namespace INT UNSIGNED NOT NULL,
  event_page_title VARBINARY(255) NOT NULL,
  event_page_wiki VARBINARY(64) NOT NULL,
  event_chat_url BLOB NOT NULL,
  event_tracking_tool VARBINARY(255) NOT NULL,
  event_tracking_url BLOB NOT NULL,
  event_status INT NOT NULL,
  event_start BINARY(14) NOT NULL,
  event_end BINARY(14) NOT NULL,
  event_type VARBINARY(255) NOT NULL,
  event_meeting_type INT NOT NULL,
  event_meeting_url BLOB NOT NULL,
  event_meeting_country VARBINARY(255) NOT NULL,
  event_meeting_address BLOB NOT NULL,
  event_created_at BINARY(14) NOT NULL,
  event_last_edit BINARY(14) NOT NULL,
  event_deleted_at BINARY(14) DEFAULT NULL,
  UNIQUE INDEX event_page (
    event_page_wiki, event_page_namespace,
    event_page_title
  ),
  PRIMARY KEY(event_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_participants (
  cep_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  cep_event_id BIGINT UNSIGNED NOT NULL,
  cep_user_id INT UNSIGNED NOT NULL,
  PRIMARY KEY(cep_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ce_organizers (
  ceo_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceo_event_id BIGINT UNSIGNED NOT NULL,
  ceo_user_id INT UNSIGNED NOT NULL,
  ceo_role_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(ceo_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/ceo_roles (
  ceor_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ceor_name VARBINARY(255) NOT NULL,
  PRIMARY KEY(ceor_id)
) /*$wgDBTableOptions*/;
