-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklist_pages.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_worklist_pages (
  cewp_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cewp_wiki VARCHAR(64) NOT NULL,
  cewp_page_prefixedtext BLOB NOT NULL,
  cewp_user_id INTEGER UNSIGNED NOT NULL,
  cewp_cew_id INTEGER UNSIGNED NOT NULL,
  cewp_timestamp BLOB NOT NULL
);

CREATE INDEX ce_worklist_pages_cewp_cew_id ON /*_*/ce_worklist_pages (cewp_cew_id);

CREATE UNIQUE INDEX ce_worklist_pages_wiki_page_cew_id ON /*_*/ce_worklist_pages (
  cewp_wiki, cewp_page_prefixedtext,
  cewp_cew_id
);
