-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_event_contributions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_event_contributions (
  cec_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cec_event_id BIGINT UNSIGNED NOT NULL,
  cec_user_id BIGINT UNSIGNED NOT NULL,
  cec_user_name BLOB DEFAULT NULL,
  cec_wiki VARCHAR(64) NOT NULL,
  cec_page_id INTEGER UNSIGNED NOT NULL,
  cec_page_prefixedtext BLOB NOT NULL,
  cec_revision_id BIGINT UNSIGNED NOT NULL,
  cec_edit_flags INTEGER NOT NULL,
  cec_bytes_delta INTEGER NOT NULL,
  cec_links_delta SMALLINT NOT NULL,
  cec_timestamp BLOB NOT NULL,
  cec_deleted SMALLINT NOT NULL
);

CREATE INDEX cec_wiki_page_id ON /*_*/ce_event_contributions (cec_wiki, cec_page_id);

CREATE INDEX cec_event_user ON /*_*/ce_event_contributions (cec_event_id, cec_user_id);

CREATE INDEX cec_user_id_name ON /*_*/ce_event_contributions (cec_user_id, cec_user_name);
