-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_invitation_list_users.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_invitation_list_users (
  ceilu_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceilu_user_id INTEGER NOT NULL, ceilu_ceil_id BIGINT UNSIGNED NOT NULL,
  ceilu_score INTEGER NOT NULL
);

CREATE INDEX ce_invitation_list_users_ceil_id ON /*_*/ce_invitation_list_users (ceilu_ceil_id);

CREATE INDEX ce_invitation_list_users_ceilu_user_id ON /*_*/ce_invitation_list_users (ceilu_user_id);
