-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_invitation_lists.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_invitation_lists (
  ceil_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceil_name BLOB NOT NULL, ceil_event_id BIGINT UNSIGNED DEFAULT NULL,
  ceil_status INTEGER NOT NULL, ceil_user_id INTEGER NOT NULL,
  ceil_wiki BLOB NOT NULL, ceil_created_at BLOB NOT NULL
);

CREATE INDEX ce_invitation_lists_event_id ON /*_*/ce_invitation_lists (ceil_event_id);

CREATE INDEX ce_invitation_lists_wiki ON /*_*/ce_invitation_lists (ceil_wiki);

CREATE INDEX ce_invitation_lists_user_wiki ON /*_*/ce_invitation_lists (ceil_user_id, ceil_wiki);
