-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_invitation_list_articles.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_invitation_list_articles (
  ceila_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceila_page_id INTEGER UNSIGNED NOT NULL,
  ceila_page_title BLOB NOT NULL, ceila_ceil_id BIGINT UNSIGNED NOT NULL
);

CREATE INDEX ce_invitation_list_articles_ceil_id ON /*_*/ce_invitation_list_articles (ceila_ceil_id);
