-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-change_event_type.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__campaign_events AS
SELECT
  event_id,
  event_name,
  event_page_namespace,
  event_page_title,
  event_page_wiki,
  event_page_prefixedtext,
  event_chat_url,
  event_status,
  event_timezone,
  event_start_local,
  event_start_utc,
  event_end_local,
  event_end_utc,
  event_meeting_type,
  event_meeting_url,
  event_created_at,
  event_last_edit,
  event_deleted_at,
  event_is_test_event
FROM /*_*/campaign_events;

DROP TABLE /*_*/campaign_events;


CREATE TABLE /*_*/campaign_events (
  event_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  event_name BLOB NOT NULL, event_page_namespace INTEGER UNSIGNED NOT NULL,
  event_page_title BLOB NOT NULL, event_page_wiki BLOB NOT NULL,
  event_page_prefixedtext BLOB NOT NULL,
  event_chat_url BLOB NOT NULL, event_status INTEGER NOT NULL,
  event_timezone BLOB NOT NULL, event_start_local BLOB NOT NULL,
  event_start_utc BLOB NOT NULL, event_end_local BLOB NOT NULL,
  event_end_utc BLOB NOT NULL, event_meeting_type INTEGER NOT NULL,
  event_meeting_url BLOB NOT NULL, event_created_at BLOB NOT NULL,
  event_last_edit BLOB NOT NULL, event_deleted_at BLOB DEFAULT NULL,
  event_is_test_event SMALLINT DEFAULT 0 NOT NULL,
  event_types INTEGER DEFAULT 0 NOT NULL
);

INSERT INTO /*_*/campaign_events (
  event_id, event_name, event_page_namespace,
  event_page_title, event_page_wiki,
  event_page_prefixedtext, event_chat_url,
  event_status, event_timezone, event_start_local,
  event_start_utc, event_end_local,
  event_end_utc, event_meeting_type,
  event_meeting_url, event_created_at,
  event_last_edit, event_deleted_at,
  event_is_test_event
)
SELECT
  event_id,
  event_name,
  event_page_namespace,
  event_page_title,
  event_page_wiki,
  event_page_prefixedtext,
  event_chat_url,
  event_status,
  event_timezone,
  event_start_local,
  event_start_utc,
  event_end_local,
  event_end_utc,
  event_meeting_type,
  event_meeting_url,
  event_created_at,
  event_last_edit,
  event_deleted_at,
  event_is_test_event
FROM
  /*_*/__temp__campaign_events;

DROP TABLE /*_*/__temp__campaign_events;

CREATE UNIQUE INDEX event_page ON /*_*/campaign_events (
  event_page_wiki, event_page_namespace,
  event_page_title
);

CREATE INDEX event_id_deleted ON /*_*/campaign_events (event_id, event_deleted_at);

CREATE INDEX event_timezone_id ON /*_*/campaign_events (event_timezone, event_id);
