-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_event_topics.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_event_topics (
  ceet_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceet_event_id BIGINT UNSIGNED NOT NULL,
  ceet_topic BLOB NOT NULL
);

CREATE UNIQUE INDEX ce_event_topics_event_id_topic ON /*_*/ce_event_topics (ceet_event_id, ceet_topic);
