-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce-event-goals.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_event_goals (
  ceeg_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceeg_event_id BIGINT UNSIGNED NOT NULL,
  ceeg_goals BLOB NOT NULL
);

CREATE INDEX ceeg_event_id ON /*_*/ce_event_goals (ceeg_event_id);
