-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-ce_worklists.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ce_worklists (
  cew_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cew_wiki VARCHAR(64) NOT NULL,
  cew_page_id INTEGER UNSIGNED NOT NULL,
  cew_page_prefixedtext BLOB NOT NULL,
  cew_user_id INTEGER UNSIGNED NOT NULL,
  cew_username BLOB DEFAULT NULL,
  cew_timestamp BLOB NOT NULL,
  cew_content_rev BIGINT UNSIGNED DEFAULT NULL
);

CREATE INDEX ce_worklists_user_id ON /*_*/ce_worklists (cew_user_id);

CREATE UNIQUE INDEX ce_worklists_wiki_page_id ON /*_*/ce_worklists (cew_wiki, cew_page_id);
