-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db_patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/campaign_events (
  event_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  event_name BLOB NOT NULL, event_page_namespace INTEGER UNSIGNED NOT NULL,
  event_page_title BLOB NOT NULL, event_page_wiki BLOB NOT NULL,
  event_page_prefixedtext BLOB NOT NULL,
  event_chat_url BLOB NOT NULL, event_status INTEGER NOT NULL,
  event_timezone BLOB NOT NULL, event_start_local BLOB NOT NULL,
  event_start_utc BLOB NOT NULL, event_end_local BLOB NOT NULL,
  event_end_utc BLOB NOT NULL, event_type BLOB NOT NULL,
  event_meeting_type INTEGER NOT NULL,
  event_meeting_url BLOB NOT NULL, event_created_at BLOB NOT NULL,
  event_last_edit BLOB NOT NULL, event_deleted_at BLOB DEFAULT NULL,
  event_is_test_event SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX event_page ON /*_*/campaign_events (
  event_page_wiki, event_page_namespace,
  event_page_title
);

CREATE INDEX event_id_deleted ON /*_*/campaign_events (event_id, event_deleted_at);

CREATE INDEX event_timezone_id ON /*_*/campaign_events (event_timezone, event_id);


CREATE TABLE /*_*/ce_participants (
  cep_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cep_event_id BIGINT UNSIGNED NOT NULL,
  cep_user_id INTEGER UNSIGNED NOT NULL,
  cep_private BOOLEAN NOT NULL, cep_registered_at BLOB NOT NULL,
  cep_unregistered_at BLOB DEFAULT NULL,
  cep_first_answer_timestamp BLOB DEFAULT NULL,
  cep_aggregation_timestamp BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX cep_event_participant ON /*_*/ce_participants (cep_event_id, cep_user_id);

CREATE INDEX cep_event_unregistered ON /*_*/ce_participants (
  cep_event_id, cep_unregistered_at
);

CREATE INDEX cep_user_unregistered_event ON /*_*/ce_participants (
  cep_user_id, cep_unregistered_at,
  cep_event_id
);


CREATE TABLE /*_*/ce_organizers (
  ceo_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceo_event_id BIGINT UNSIGNED NOT NULL,
  ceo_user_id INTEGER UNSIGNED NOT NULL,
  ceo_roles BIGINT UNSIGNED NOT NULL,
  ceo_created_at BLOB NOT NULL, ceo_deleted_at BLOB DEFAULT NULL,
  ceo_agreement_timestamp BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX ceo_event_user ON /*_*/ce_organizers (ceo_event_id, ceo_user_id);

CREATE INDEX ceo_user_event ON /*_*/ce_organizers (ceo_user_id, ceo_event_id);


CREATE TABLE /*_*/ce_address (
  cea_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cea_full_address BLOB NOT NULL, cea_country BLOB DEFAULT NULL
);


CREATE TABLE /*_*/ce_event_address (
  ceea_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceea_event BIGINT UNSIGNED NOT NULL,
  ceea_address BIGINT UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX ceea_event_address ON /*_*/ce_event_address (ceea_event, ceea_address);


CREATE TABLE /*_*/ce_tracking_tools (
  cett_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cett_event BIGINT UNSIGNED NOT NULL,
  cett_tool_id INTEGER NOT NULL, cett_tool_event_id BLOB NOT NULL,
  cett_sync_status INTEGER NOT NULL,
  cett_last_sync BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX cett_event_tool_teid ON /*_*/ce_tracking_tools (
  cett_event, cett_tool_id, cett_tool_event_id
);


CREATE TABLE /*_*/ce_event_questions (
  ceeq_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceeq_event_id BIGINT UNSIGNED NOT NULL,
  ceeq_question_id INTEGER UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX ceeq_event_question ON /*_*/ce_event_questions (ceeq_event_id, ceeq_question_id);


CREATE TABLE /*_*/ce_question_answers (
  ceqa_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceqa_event_id BIGINT UNSIGNED NOT NULL,
  ceqa_user_id INTEGER UNSIGNED NOT NULL,
  ceqa_question_id INTEGER UNSIGNED NOT NULL,
  ceqa_answer_option INTEGER UNSIGNED DEFAULT NULL,
  ceqa_answer_text BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX ceqa_event_user_question ON /*_*/ce_question_answers (
  ceqa_event_id, ceqa_user_id, ceqa_question_id
);


CREATE TABLE /*_*/ce_question_aggregation (
  ceqag_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceqag_event_id BIGINT UNSIGNED NOT NULL,
  ceqag_question_id INTEGER UNSIGNED NOT NULL,
  ceqag_answer_option INTEGER UNSIGNED NOT NULL,
  ceqag_answers_amount INTEGER UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX ceqag_event_question_option ON /*_*/ce_question_aggregation (
  ceqag_event_id, ceqag_question_id,
  ceqag_answer_option
);


CREATE TABLE /*_*/ce_invitation_lists (
  ceil_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceil_name BLOB NOT NULL, ceil_event_id BIGINT UNSIGNED DEFAULT NULL,
  ceil_status INTEGER NOT NULL, ceil_user_id INTEGER NOT NULL,
  ceil_wiki BLOB NOT NULL, ceil_created_at BLOB NOT NULL
);

CREATE INDEX ce_invitation_lists_event_id ON /*_*/ce_invitation_lists (ceil_event_id);

CREATE INDEX ce_invitation_lists_wiki ON /*_*/ce_invitation_lists (ceil_wiki);

CREATE INDEX ce_invitation_lists_user_wiki ON /*_*/ce_invitation_lists (ceil_user_id, ceil_wiki);


CREATE TABLE /*_*/ce_worklist_articles (
  cewa_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cewa_page_id INTEGER UNSIGNED NOT NULL,
  cewa_page_title BLOB NOT NULL, cewa_ceil_id BIGINT UNSIGNED NOT NULL
);

CREATE INDEX ce_worklist_articles_ceil_id ON /*_*/ce_worklist_articles (cewa_ceil_id);


CREATE TABLE /*_*/ce_invitation_list_users (
  ceilu_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceilu_user_id INTEGER NOT NULL, ceilu_ceil_id BIGINT UNSIGNED NOT NULL,
  ceilu_score INTEGER NOT NULL
);

CREATE INDEX ce_invitation_list_users_ceil_id ON /*_*/ce_invitation_list_users (ceilu_ceil_id);

CREATE INDEX ce_invitation_list_users_ceilu_user_id ON /*_*/ce_invitation_list_users (ceilu_user_id);


CREATE TABLE /*_*/ce_event_wikis (
  ceew_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceew_event_id BIGINT UNSIGNED NOT NULL,
  ceew_wiki BLOB NOT NULL
);

CREATE UNIQUE INDEX ce_event_wikis_event_id_wiki ON /*_*/ce_event_wikis (ceew_event_id, ceew_wiki);


CREATE TABLE /*_*/ce_event_topics (
  ceet_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceet_event_id BIGINT UNSIGNED NOT NULL,
  ceet_topic BLOB NOT NULL
);

CREATE UNIQUE INDEX ce_event_topics_event_id_topic ON /*_*/ce_event_topics (ceet_event_id, ceet_topic);
