-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db_patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/campaign_events (
  event_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  event_name BLOB NOT NULL, event_page_namespace INTEGER UNSIGNED NOT NULL,
  event_page_title BLOB NOT NULL, event_page_wiki BLOB NOT NULL,
  event_page_prefixedtext BLOB NOT NULL,
  event_chat_url BLOB NOT NULL, event_status INTEGER NOT NULL,
  event_timezone BLOB NOT NULL, event_start_local BLOB NOT NULL,
  event_start_utc BLOB NOT NULL, event_end_local BLOB NOT NULL,
  event_end_utc BLOB NOT NULL, event_type BLOB NOT NULL,
  event_meeting_type INTEGER NOT NULL,
  event_meeting_url BLOB NOT NULL, event_created_at BLOB NOT NULL,
  event_last_edit BLOB NOT NULL, event_deleted_at BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX event_page ON /*_*/campaign_events (
  event_page_wiki, event_page_namespace,
  event_page_title
);

CREATE INDEX event_id_deleted ON /*_*/campaign_events (event_id, event_deleted_at);

CREATE INDEX event_timezone_id ON /*_*/campaign_events (event_timezone, event_id);


CREATE TABLE /*_*/ce_participants (
  cep_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cep_event_id BIGINT UNSIGNED NOT NULL,
  cep_user_id INTEGER UNSIGNED NOT NULL,
  cep_private BOOLEAN NOT NULL, cep_registered_at BLOB NOT NULL,
  cep_unregistered_at BLOB DEFAULT NULL,
  cep_first_answer_timestamp BLOB DEFAULT NULL,
  cep_aggregation_timestamp BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX cep_event_participant ON /*_*/ce_participants (cep_event_id, cep_user_id);

CREATE INDEX cep_event_unregistered ON /*_*/ce_participants (
  cep_event_id, cep_unregistered_at
);

CREATE INDEX cep_user_unregistered_event ON /*_*/ce_participants (
  cep_user_id, cep_unregistered_at,
  cep_event_id
);

CREATE INDEX cep_aggregation ON /*_*/ce_participants (cep_aggregation_timestamp);


CREATE TABLE /*_*/ce_organizers (
  ceo_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceo_event_id BIGINT UNSIGNED NOT NULL,
  ceo_user_id INTEGER UNSIGNED NOT NULL,
  ceo_roles BIGINT UNSIGNED NOT NULL,
  ceo_created_at BLOB NOT NULL, ceo_deleted_at BLOB DEFAULT NULL,
  ceo_agreement_timestamp BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX ceo_event_user ON /*_*/ce_organizers (ceo_event_id, ceo_user_id);

CREATE INDEX ceo_user_event ON /*_*/ce_organizers (ceo_user_id, ceo_event_id);


CREATE TABLE /*_*/ce_address (
  cea_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cea_full_address BLOB NOT NULL, cea_country BLOB DEFAULT NULL
);


CREATE TABLE /*_*/ce_event_address (
  ceea_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceea_event BIGINT UNSIGNED NOT NULL,
  ceea_address BIGINT UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX ceea_event_address ON /*_*/ce_event_address (ceea_event, ceea_address);


CREATE TABLE /*_*/ce_tracking_tools (
  cett_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cett_event BIGINT UNSIGNED NOT NULL,
  cett_tool_id INTEGER NOT NULL, cett_tool_event_id BLOB NOT NULL,
  cett_sync_status INTEGER NOT NULL,
  cett_last_sync BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX cett_event_tool_teid ON /*_*/ce_tracking_tools (
  cett_event, cett_tool_id, cett_tool_event_id
);


CREATE TABLE /*_*/ce_event_questions (
  ceeq_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceeq_event_id BIGINT UNSIGNED NOT NULL,
  ceeq_question_id INTEGER UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX ceeq_event_question ON /*_*/ce_event_questions (ceeq_event_id, ceeq_question_id);


CREATE TABLE /*_*/ce_question_answers (
  ceqa_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceqa_event_id BIGINT UNSIGNED NOT NULL,
  ceqa_user_id INTEGER UNSIGNED NOT NULL,
  ceqa_question_id INTEGER UNSIGNED NOT NULL,
  ceqa_answer_option INTEGER UNSIGNED DEFAULT NULL,
  ceqa_answer_text BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX ceqa_event_user_question ON /*_*/ce_question_answers (
  ceqa_event_id, ceqa_user_id, ceqa_question_id
);


CREATE TABLE /*_*/ce_question_aggregation (
  ceqag_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ceqag_event_id BIGINT UNSIGNED NOT NULL,
  ceqag_question_id INTEGER UNSIGNED NOT NULL,
  ceqag_answer_option INTEGER UNSIGNED NOT NULL,
  ceqag_answers_amount INTEGER UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX ceqag_event_question ON /*_*/ce_question_aggregation (
  ceqag_event_id, ceqag_question_id
);
