<?php

declare( strict_types=1 );

namespace MediaWiki\Extension\CampaignEvents\Worklist;

/**
 * Base interface for classes that provide a paginated lookup for the contents of a worklist.
 * Implementations should accept the worklist page in the constructor, as different worklists might need different
 * implementations.
 */
interface IWorklistPagesLookup {
	public const string SORT_TITLE = 'sort_title';
	public const string SORT_WIKI = 'sort_wiki';
	public const string SORT_TIMESTAMP = 'sort_timestamp';

	public const array VALID_SORTS = [ self::SORT_TITLE, self::SORT_WIKI, self::SORT_TIMESTAMP ];

	public const bool DIR_ASCENDING = true;
	public const bool DIR_DESCENDING = false;

	public const bool BACKWARDS = true;
	public const bool NOT_BACKWARDS = false;

	public const string PAGINATION_PREV = 'prev';
	public const string PAGINATION_NEXT = 'next';
	public const string PAGINATION_CUR = 'cur';
	public const string PAGINATION_FIRST = 'first';
	public const string PAGINATION_LAST = 'last';

	/**
	 * Returns a list of worklist pages for the specified pagination parameters, as well as pagination offsets to get
	 * other result pages; the caller is responsible for setting $isBackwards to the appropriate value when navigating.
	 * Different implementations may use different sorting algorithms; natural sort is preferred when possible. Also,
	 * different implementations may use different stable tiebreakers as the rightmost field of each sort type (such as
	 * a surrogate primary key). As a consequence of these two facts, offsets generated by different implementations
	 * are not intercompatible, in principle; however, this should rarely be an issue with real data.
	 *
	 * Offsets are only set if their respective result page exists, and may otherwise be null for extreme pages.
	 * The format for offsets is compatible with that used by IndexPager; however, callers should not rely on this, and
	 * instead treat the offsets as opaque values to be fed back to this method.
	 *
	 * @param string $sort One of the self::SORT_* constants
	 * @param positive-int $limit Maximum number of entries to return. Implementations are not forced to honor this
	 *   number, and may return fewer results than asked. Callers are responsible for validation
	 * @param ?string $offset As returned by this method. Invalid offsets are silently discarded.
	 * @param bool $direction {@link self::DIR_ASCENDING} or {@link self::DIR_DESCENDING}
	 * @param bool $isBackwards {@link self::BACKWARDS} or {@link self::NOT_BACKWARDS}, when set we start listing
	 *   results from the last page, but still in the specified direction.
	 * @return array{
	 *     result:list<array{wiki:string,prefixedtext:string,timestamp:int|null}>,
	 *     paginationOffsets:array{prev?:string|null,next?:string|null,cur?:string|null,first?:string|null,last?:string|null}
	 * } Where timestamps are UNIX, and the keys in paginationOffsets are the self::PAGINATION_* constants.
	 */
	public function getWorklistPages(
		string $sort,
		int $limit,
		?string $offset,
		bool $direction,
		bool $isBackwards,
	): array;
}
